---
files:
- path: "C:/Users/pokef/Documents/PokeMeetup/core/build.gradle"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/FileSystemDelegate.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/CreatureCaptureGame.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/Quadtree.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/TileType.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/TimeUtils.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/GameLogger.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/PerlinNoise.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/BattleAssets.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/DialogStyles.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/ScalingUtils.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/TextureUtils.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/PasswordUtils.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/TextureManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/UUIDSerializer.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/GameInitializer.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/ResponsiveLayout.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/AssetManagerSingleton.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/storage/JsonConfig.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/storage/GameFileSystem.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/storage/DesktopFileSystem.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/utils/storage/InventoryConverter.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/Player.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/InputHandler.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/PickupActionHandler.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/AndroidMovementController.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/battle/BattleResult.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/battle/BattleCompletionHandler.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/battle/BattleInitiationHandler.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/data/ItemData.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/data/WorldData.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/data/PlayerData.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/data/PokemonData.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/data/BlockSaveData.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/gameplay/PlayerAnimations.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/gameplay/PokemonAnimations.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/gameplay/SpawnPointValidator.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/servers/GamePlugin.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/system/servers/PluginContext.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/server/deployment/ServerLauncher.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/server/deployment/ConnectionState.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/server/deployment/DeploymentHelper.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/server/deployment/ConnectionManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/server/deployment/ServerFileDelegate.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/GameScreen.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/LoginScreen.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/LoadingScreen.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/InventoryScreen.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/ModeSelectionScreen.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/WorldSelectionScreen.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/GameMenu.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/HotbarUI.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/BattleTable.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/BuildModeUI.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/PokemonPartyUI.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/InventorySlotUI.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/ServerListEntry.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/screens/otherui/StarterSelectionTable.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/audio/AudioManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/blocks/BlockManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/blocks/PlaceableBlock.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/chat/Command.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/chat/ChatSystem.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/chat/Permission.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/chat/TeamSystem.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/chat/HelpCommand.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/chat/TeleportManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/managers/BiomeManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/managers/BiomeRenderer.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/managers/DatabaseManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/managers/BiomeTransitionResult.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/OtherPlayer.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/ServerPlayer.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/PlayerManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/PlayerConnection.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/oldsystems/PlayerDataV1.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/pokemon/Pokemon.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/pokemon/WildPokemon.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/pokemon/PokemonParty.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/pokemon/PokemonDespawnAnimation.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/client/GameClient.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/client/GameClientSingleton.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/network/NetworkedTree.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/network/NetworkProtocol.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/network/NetworkedPokeball.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/network/NetworkedWorldObject.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/GameServer.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/PlayerEvents.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/DialogListener.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/GameStateHandler.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/ServerStorageSystem.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/config/ServerConfigManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/config/ServerConnectionConfig.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/Entity.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/EntityType.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/AIController.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/EntityEvents.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/EntityFactory.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/EntityManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/CreatureEntity.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/PokeballEntity.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/entity/SimpleAIController.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/events/ServerEvent.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/events/EventManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/events/EventListener.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/events/BaseServerEvent.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/plugin/PluginConfig.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/plugin/PluginLoader.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/plugin/ServerPlugin.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/plugin/PluginManager.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/plugin/JarPluginLoader.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/storage/FileStorage.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/core/src/main/java/io/github/pokemeetup/multiplayer/server/storage/StorageSystem.java"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/data/moves.json"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/data/biomes.json"
  readOnly: false
- path: "C:/Users/pokef/Documents/PokeMeetup/data/pokemon.json"
  readOnly: false
